function BBGUI

%pragma functions:
%#function bbCallback dsetCallback

ssize = get(0,'screensize');

figHan = figure('name','Branch & Bound to Find Consis. Meas.',...
                'numbertitle','off',...
                'menubar','none');

x=1/7.5;
p1 = uipanel(figHan,'title','DCDataset',...
                    'position',x*[0.5 3 6.5 4]);
p2 = uipanel(figHan,'title','ParameterDomain',...
                    'position',x*[0.5 2 6.5 1]);
bt = uicontrol(figHan,'style','pushbutton',...
                      'string','Find Consis. Meas.',...
                      'units','normalized', ...
                      'position',x*[2 0.5 3.5 1],...
                      'callback',@bbCallback);

modAss = uicontrol(p1,'style','text',...
                   'horizontalalignment','right',...
                   'string','ResponseModel: ',...
                   'units','normalized',...
                   'position',[0.1,0.7 0.4 0.2]);
modAssE = uicontrol(p1,'style','edit',...
                    'horizontalalignment','left',...
                    'units','normalized',...
                    'position',[0.5 0.7 0.4 0.2],...
                    'backgroundcolor',[0.9 0.9 0.9]);

expAss = uicontrol(p1,'style','text',...
                   'horizontalalignment','right',...
                   'string','ResponseObservation: ',...
                   'units','normalized',...
                   'position',[0.1,0.5 0.4 0.2]);
expAssE = uicontrol(p1,'style','edit',...
                    'horizontalalignment','left',...
                    'units','normalized',...
                    'position',[0.5 0.5 0.4 0.2],...
                    'backgroundcolor',[0.9 0.9 0.9]);

bt2 = uicontrol('style','pushbutton',...
                'parent',p1,...
                'string','Make DCDataset Unit',...
                'units','normalized',...
                'position',[0.33 0.25 0.33 0.2],...
                'callback',@dsetCallback);

total = uicontrol(p1,'style','text',...
                  'string','Total # of units in DCDataset: 0',...
                  'units','normalized',...
                  'position',[0.1,0.1,0.8,0.1],...
                  'horizontalalignment','center');

param = uicontrol(p2,'style','edit',...
                  'units','normalized',...
                  'position',[0.1 0.1 0.8 0.8],...
                  'horizontalalignment','left',...
                  'backgroundcolor',[0.9 0.9 0.9]);

setappdata(figHan,'hans',{modAssE,expAssE,bt2,total,param});
setappdata(figHan,'dset',[]);

%---------------------------------------
function bbCallback(obj,eventD)

opt = set(Options,'numComp',0,'diagnostics','off','tol',0.03,...
    'diagName','praj1','activeParamCutOff',0.02,'magObjectFunTol',0.001,...
    'constraints',[1 1 0 0], 'fitType', inf,'plot','off');
Dset = getappdata(gcf,'dset');
hans = getappdata(gcf,'hans');
P = evalin('base',get(hans{5},'string'));
iter = bb2(Dset,P,opt);

assignin(base,'iter',iter);

msgbox(['Done!  There is a variable in the base workspace called ' ...
        '''iter'' that will contain all the information for branch' ...
        'and bound.']);
  
%---------------------------------------
function dsetCallback(obj,eventD)

hans = getappdata(gcf,'hans');
dset = getappdata(gcf,'dset');

model = evalin('base',get(hans{1},'string'));
exp = evalin('base',get(hans{2},'string'));
DsetUnit = DClab.DCDataset(model,exp);
dset = [dset; DsetUnit];

setappdata(gcf,'dset',dset);

set(hans{4},'string',['Total # of units in DCDataset: ' num2str(length(dset))]);
